import Navbar from "@/components/Screen/Shared/Navbar";
import "../styles/globals.css";
import Footer from "@/components/Screen/Shared/Footer";
import Menu from "@/components/Screen/Shared/Menu";

export const metadata = {
  title: "University",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <Menu />
        <main className="container_fluid">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
